pipeline {
    agent any

    parameters {
        choice(name: 'terraformAction',
               choices: ['apply', 'destroy'],
               description: 'Choose the Terraform action to perform')
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {

        stage('checkout') {
            steps {
                dir("terraform") {
                    git branch: 'infra',
                        url: 'https://github.com/rashmigmr13-eng/gen-ai.git'
                }
            }
        }

        stage('Plan') {
            steps {
                dir('terraform/test-eks') {
                    sh 'terraform init'
                    sh 'terraform plan -out tfplan'
                    sh 'terraform show -no-color tfplan > tfplan.txt'
                }
            }
        }

        stage('Approval') {
            steps {
                script {
                    def plan = readFile 'terraform/test-eks/tfplan.txt'
                    input message: "Do you want to proceed with the Terraform action?",
                          parameters: [
                              text(name: 'Plan',
                                   description: 'Please review the plan',
                                   defaultValue: plan)
                          ]
                }
            }
        }

        stage('Apply or Destroy') {
            when {
                expression {
                    params.terraformAction == 'apply' ||
                    params.terraformAction == 'destroy'
                }
            }
            steps {
                dir('terraform/test-eks') {
                    script {
                        if (params.terraformAction == 'apply') {
                            sh 'terraform apply -input=false tfplan'
                        } else {
                            sh 'terraform destroy -auto-approve'
                        }
                    }
                }
            }
        }
    }
}
